version: '3.8'

services:
  api:
    build:
      context: .
      args:
        - NODE_ENV=development
    container_name: futboleando_api
    ports:
      - "4000:3000"
      - "9230:9229"
    depends_on:
      - redis
    env_file:
      - .env
    restart: always
    working_dir: /app
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - NODE_OPTIONS=--enable-source-maps
      - CHOKIDAR_USEPOLLING=1
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
      - futboleando_node_modules:/app/node_modules
    command: >
      node --inspect=0.0.0.0:9229 --nolazy
           -r ts-node/register/transpile-only
           src/index.ts

  redis:
    image: redis:alpine
    container_name: futboleando_redis
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  futboleando_node_modules: